/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Compra.java
 *
 * Created on 11-03-2012, 01:53:02 PM
 */
package soprafamrv;

import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import oracle.jdbc.OracleCallableStatement;
import soprafamrv.BD.Conexion;
import soprafamrv.SISTEMA.compra;
import soprafamrv.SISTEMA.miPanel;

/**
 *
 * @author Administrador
 */
public class Compra extends javax.swing.JInternalFrame {

    /** Creates new form Compra */
    public Compra(){
        initComponents();
        CargarPanel();
        this.JLIDPROVEEDOR.setVisible(false);
        this.JLID_REPUESTO.setVisible(false);
        
    }
    
    private void HabilitarCampos(){
        this.JCADMINISTRADOR.setEnabled(true);
        this.JCPROVEEDOR.setEnabled(true);
        this.JTXDETALLE.setEnabled(true);
        
    }
    private void DeshabilitarCampos(){
        this.JCADMINISTRADOR.setEnabled(false);
        this.JCPROVEEDOR.setEnabled(false);
        this.JTXDETALLE.setEnabled(false);
        
    
    }
    
    private void LimpiarCampos(){
         this.JTRepueSelec.setText(null);
         this.JTDESCREPU.setText(null);
         this.JFCantidad.setText(null);       
         this.JTObservaciones.setText(null);
         JPanelImagen.removeAll();
         JPanelImagen.repaint();
    }
    
    private void ResetearCampos(){
        this.JCADMINISTRADOR.setSelectedIndex(0);
        this.JCPROVEEDOR.setSelectedIndex(0);
        this.JTXDETALLE.setText(null);
        this.JFNROFACTURA.setText(null);
    
    }
    
    private void AsignarFechaIngreso() {
        //Puedo jugar con DD MM YYYY para mostrarlos individualmente
        DateFormat dia = new SimpleDateFormat("dd");
        DateFormat mes = new SimpleDateFormat("MMMMMMMMMM");
        DateFormat ano = new SimpleDateFormat("yyyy");
        //DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Date date = new Date();

        this.TCINI1.addItem(dia.format(date));
        this.TCINI2.addItem(mes.format(date).toUpperCase());
        this.TCINI3.addItem(ano.format(date));
        this.TCINI1.setSelectedIndex(1);
        this.TCINI2.setSelectedIndex(1);
        this.TCINI3.setSelectedIndex(1);
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        
        System.out.println("Termino ingreso años");

    }
    private void CargarPanel(){
        try {
            String query = "Select * from buscaradministrador";
            ResultSet rs = Conexion.ejecutarQuery(query);
            while (rs.next()) {                
                this.JCADMINISTRADOR.addItem(rs.getString("RUT_ADMINISTRADOR")+ " - " +rs.getString("NOMBRE")+ " " +rs.getString("APELLIDO_PATERNO")+ " " +rs.getString("APELLIDO_MATERNO"));
                }
            String query2 = "Select * from buscarproveedor";
            ResultSet rs2 = Conexion.ejecutarQuery(query2);
            while (rs2.next()){
                this.JCPROVEEDOR.addItem(rs2.getString("NOMBRE"));
                }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Compra.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    
    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JFNROFACTURA = new javax.swing.JFormattedTextField();
        TCINI1 = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        TCINI2 = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        TCINI3 = new javax.swing.JComboBox();
        JCPROVEEDOR = new javax.swing.JComboBox();
        JCADMINISTRADOR = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTXDETALLE = new javax.swing.JTextArea();
        JLIDPROVEEDOR = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        JLREPDISPO = new java.awt.List();
        JLREPINGRESADO = new java.awt.List();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        JTRepueSelec = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTDESCREPU = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        JFCantidad = new javax.swing.JFormattedTextField();
        jPanel5 = new javax.swing.JPanel();
        JPanelImagen = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        JTObservaciones = new javax.swing.JTextArea();
        jButton9 = new javax.swing.JButton();
        JFNROFACTURA2 = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        JLID_REPUESTO = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();

        setClosable(true);
        setMaximizable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(soprafamrv.SOPRAFAMRVApp0.class).getContext().getResourceMap(Compra.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setName("jToolBar1"); // NOI18N

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setName("jButton1"); // NOI18N
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setName("jButton2"); // NOI18N
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setName("jButton3"); // NOI18N
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton3);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel1.border.title"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel2.border.title"))); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        try {
            JFNROFACTURA.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###############")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JFNROFACTURA.setEnabled(false);
        JFNROFACTURA.setName("JFNROFACTURA"); // NOI18N

        TCINI1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Día" }));
        TCINI1.setEnabled(false);
        TCINI1.setName("TCINI1"); // NOI18N

        jLabel17.setText(resourceMap.getString("jLabel17.text")); // NOI18N
        jLabel17.setName("jLabel17"); // NOI18N

        TCINI2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mes" }));
        TCINI2.setEnabled(false);
        TCINI2.setName("TCINI2"); // NOI18N

        jLabel18.setText(resourceMap.getString("jLabel18.text")); // NOI18N
        jLabel18.setName("jLabel18"); // NOI18N

        TCINI3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Año" }));
        TCINI3.setEnabled(false);
        TCINI3.setName("TCINI3"); // NOI18N

        JCPROVEEDOR.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar Proveedor" }));
        JCPROVEEDOR.setEnabled(false);
        JCPROVEEDOR.setName("JCPROVEEDOR"); // NOI18N
        JCPROVEEDOR.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JCPROVEEDORItemStateChanged(evt);
            }
        });

        JCADMINISTRADOR.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar Administrador" }));
        JCADMINISTRADOR.setEnabled(false);
        JCADMINISTRADOR.setName("JCADMINISTRADOR"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        JTXDETALLE.setColumns(20);
        JTXDETALLE.setLineWrap(true);
        JTXDETALLE.setRows(5);
        JTXDETALLE.setEnabled(false);
        JTXDETALLE.setName("JTXDETALLE"); // NOI18N
        jScrollPane1.setViewportView(JTXDETALLE);

        JLIDPROVEEDOR.setText(resourceMap.getString("JLIDPROVEEDOR.text")); // NOI18N
        JLIDPROVEEDOR.setName("JLIDPROVEEDOR"); // NOI18N

        jButton5.setText(resourceMap.getString("jButton5.text")); // NOI18N
        jButton5.setName("jButton5"); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JCADMINISTRADOR, 0, 284, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(TCINI1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel17)
                                        .addGap(8, 8, 8)
                                        .addComponent(TCINI2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TCINI3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(JCPROVEEDOR, 0, 284, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(JFNROFACTURA, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                                        .addComponent(JLIDPROVEEDOR)
                                        .addGap(20, 20, 20))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))))
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JFNROFACTURA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(JLIDPROVEEDOR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TCINI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TCINI2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(TCINI3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JCADMINISTRADOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JCPROVEEDOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel3.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, resourceMap.getColor("jPanel3.border.titleColor"))); // NOI18N
        jPanel3.setName("jPanel3"); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel4.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, resourceMap.getColor("jPanel4.border.titleColor"))); // NOI18N
        jPanel4.setName("jPanel4"); // NOI18N

        jButton7.setText(resourceMap.getString("jButton7.text")); // NOI18N
        jButton7.setName("jButton7"); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        JLREPDISPO.setName("JLREPDISPO"); // NOI18N

        JLREPINGRESADO.setEnabled(false);
        JLREPINGRESADO.setName("JLREPINGRESADO"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLREPINGRESADO, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(JLREPDISPO, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(JLREPDISPO, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLREPINGRESADO, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jSeparator1.setName("jSeparator1"); // NOI18N

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel6.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, resourceMap.getColor("jPanel6.border.titleColor"))); // NOI18N
        jPanel6.setName("jPanel6"); // NOI18N

        JTRepueSelec.setEnabled(false);
        JTRepueSelec.setName("JTRepueSelec"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        JTDESCREPU.setColumns(20);
        JTDESCREPU.setEditable(false);
        JTDESCREPU.setLineWrap(true);
        JTDESCREPU.setRows(5);
        JTDESCREPU.setEnabled(false);
        JTDESCREPU.setName("JTDESCREPU"); // NOI18N
        jScrollPane2.setViewportView(JTDESCREPU);

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        JFCantidad.setEnabled(false);
        JFCantidad.setName("JFCantidad"); // NOI18N
        JFCantidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JFCantidadMouseExited(evt);
            }
        });
        JFCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFCantidadActionPerformed(evt);
            }
        });
        JFCantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JFCantidadFocusLost(evt);
            }
        });
        JFCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JFCantidadKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JFCantidadKeyReleased(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel5.border.title"))); // NOI18N
        jPanel5.setName("jPanel5"); // NOI18N

        JPanelImagen.setName("JPanelImagen"); // NOI18N

        javax.swing.GroupLayout JPanelImagenLayout = new javax.swing.GroupLayout(JPanelImagen);
        JPanelImagen.setLayout(JPanelImagenLayout);
        JPanelImagenLayout.setHorizontalGroup(
            JPanelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 219, Short.MAX_VALUE)
        );
        JPanelImagenLayout.setVerticalGroup(
            JPanelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 233, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        JTObservaciones.setColumns(20);
        JTObservaciones.setLineWrap(true);
        JTObservaciones.setRows(5);
        JTObservaciones.setName("JTObservaciones"); // NOI18N
        jScrollPane3.setViewportView(JTObservaciones);

        jButton9.setText(resourceMap.getString("jButton9.text")); // NOI18N
        jButton9.setName("jButton9"); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(JTRepueSelec, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addGap(18, 18, 18)
                                            .addComponent(JFCantidad, 0, 0, Short.MAX_VALUE))
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton9))
                        .addGap(39, 39, 39)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(JTRepueSelec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(JFCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9)
                .addGap(42, 42, 42))
        );

        JFNROFACTURA2.setEditable(false);
        JFNROFACTURA2.setEnabled(false);
        JFNROFACTURA2.setName("JFNROFACTURA2"); // NOI18N

        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N

        JLID_REPUESTO.setName("JLID_REPUESTO"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(JFNROFACTURA2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(JLID_REPUESTO)
                        .addGap(109, 109, 109))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(JFNROFACTURA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLID_REPUESTO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel7.border.title"))); // NOI18N
        jPanel7.setName("jPanel7"); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1254, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String query = "Select max(nro_factura) from compra";
            ResultSet rs = Conexion.ejecutarQuery(query);
            while (rs.next()) {
                if (rs.getString("max(nro_factura)") != null){
                int id = Integer.parseInt(rs.getString("max(nro_factura)"))+1;
                this.JFNROFACTURA.setText(String.valueOf(id));               
                HabilitarCampos();
                AsignarFechaIngreso();
                this.JFNROFACTURA2.setText(null);
                this.JLREPDISPO.removeAll();
                }
                else{
                this.JFNROFACTURA.setText("1");
                HabilitarCampos();
                AsignarFechaIngreso();
                }
            }
                 
        } catch (SQLException ex) {
            Logger.getLogger(Compra.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            System.out.println("INICIO DEFINICION DE VARIABLES");
            compra c = new compra();
            int NROFACTURA = Integer.parseInt(this.JFNROFACTURA.getText().trim());
            String FECHA_INICIO = this.TCINI1.getSelectedItem() + "-" + this.TCINI2.getSelectedItem() + "-" + this.TCINI3.getSelectedItem();
            String RUT_ADMIN = this.JCADMINISTRADOR.getSelectedItem().toString().substring(0, 12);
            int ID_PROVEEDOR = Integer.parseInt(this.JLIDPROVEEDOR.getText().trim());
            String DETALLE = this.JTXDETALLE.getText().trim().toUpperCase();
            
            System.out.println("Definicion formato fecha");
            SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd-MMMMMMMMMM-yyyy", new Locale("es", "ES"));
            java.sql.Date inicio = new java.sql.Date(sdf.parse(FECHA_INICIO).getTime());
            
            c.setNRO_FACTURA(NROFACTURA);
            c.setFECHA_COMPRA(inicio);
            c.setID_PROVEEDOR(ID_PROVEEDOR);
            c.setRUT_ADMINISTRADOR(RUT_ADMIN);
            c.setDETALLE(DETALLE);
            
            System.out.println("Termino Definición Variables");
            Conexion con = new Conexion();
            
            System.out.println("INICIO impresion variables asignadas");            
            System.out.println("NUM_FACTURA: " +c.getNRO_FACTURA());
            System.out.println("FECHA COMPRA: " +c.getFECHA_COMPRA());
            System.out.println("ID PROVEEDOR: " +c.getID_PROVEEDOR());
            System.out.println("RUT ADMINISTRADOR: " +c.getRUT_ADMINISTRADOR());
            System.out.println("DETALLE: " +c.getDETALLE());
            System.out.println("TERMINO impresion variables asignadas");
            
            if (!"Dia".equals(this.TCINI1.getSelectedItem().toString()) && !"Mes".equals(this.TCINI2.getSelectedItem().toString()) && !"Ano".equals(this.TCINI3.getSelectedItem().toString()) && !"Seleccionar Administrador".equals(this.JCADMINISTRADOR.getSelectedItem().toString()) && !"Seleccionar Proveedor".equals(this.JCADMINISTRADOR.getSelectedItem().toString()) && this.JTXDETALLE.getText() != null) {
                int n = JOptionPane.showConfirmDialog(rootPane, "¿Esta¡ seguro que desea Guardar?", "Mensajero", JOptionPane.YES_NO_CANCEL_OPTION);
                //n = 0 es YES, n = 1 es NO, n = 2 es Cancel
                System.out.println("numero" + JOptionPane.YES_NO_CANCEL_OPTION);
                if (n == 0) {
                    con.RegistrarCompra(c);
                    ResetearCampos();
                    DeshabilitarCampos();
                    String query5 = "Select id_repuesto, nombre from repuesto";
                    ResultSet rs5 = Conexion.ejecutarQuery(query5);
                    while (rs5.next()) {        
                        this.JLREPDISPO.add(rs5.getString("nombre"));
                    }
                    this.JLREPDISPO.setEnabled(true);
                    
                    JOptionPane.showMessageDialog(null, "Datos Ingresados Satisfactoriamente", "Mensajero", JOptionPane.INFORMATION_MESSAGE);
                    this.JFNROFACTURA2.setText(String.valueOf(NROFACTURA));
                }else if (n == 1) {
                    ResetearCampos();
                }else{
                JOptionPane.showMessageDialog(null,"Codigo: " +"Debe llenar todos los campos solicitados", "Error", JOptionPane.ERROR_MESSAGE); 
                }

            }
        } catch (SQLException ex) {
            Logger.getLogger(Compra.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(Compra.class.getName()).log(Level.SEVERE, null, ex);
        }
    
}//GEN-LAST:event_jButton5ActionPerformed

private void JCPROVEEDORItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JCPROVEEDORItemStateChanged
        try {
            String NOMBREPROVE = (String) this.JCPROVEEDOR.getSelectedItem();
            String query = "select id_proveedor from proveedor where nombre='"+NOMBREPROVE+"'";
            ResultSet rs = Conexion.ejecutarQuery(query);
            while (rs.next()){
                    try {
                        this.JLIDPROVEEDOR.setText(rs.getString("id_proveedor"));
                    } catch (SQLException ex) {
                        Logger.getLogger(Compra.class.getName()).log(Level.SEVERE, null, ex);
                    }
            
            
            }
        } catch (SQLException ex) {
            Logger.getLogger(Compra.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    
    
}//GEN-LAST:event_JCPROVEEDORItemStateChanged

private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            LimpiarCampos();
            String NOMBRE = this.JLREPDISPO.getSelectedItem();                            
            this.JTRepueSelec.setText(NOMBRE);
            Connection con = DriverManager.getConnection(Conexion.url, Conexion.usuario, Conexion.clave);
            OracleCallableStatement cs = (OracleCallableStatement) con.prepareCall("BEGIN CargaRepuestos(?,?,?,?,?); END;");
            
            System.out.println("***INICIO CARGA REPUESTO***");
            System.out.println("Setiando Parametros ENTRADA");
            cs.setString(1, NOMBRE);

            System.out.println("Setiando Parametros SALIDA");            
            cs.registerOutParameter(2, Types.INTEGER);            
            cs.registerOutParameter(3, Types.INTEGER);            
            cs.registerOutParameter(4, Types.VARCHAR);            
            cs.registerOutParameter(5, Types.BLOB);
            System.out.println("TERMINO Seteo de Parametros");                                                
            
            cs.execute();
            int IDREPUESTO = 0;
            int CANTIDAD = 0;
            String DESCRIPCION = null;
            byte[] FOTOByte;
            
            //Asignacion a las variables
            System.out.println("INICIO ASIGNACION VARIABLES OBTENIDAS DE BD");                                                
            
            IDREPUESTO = cs.getOracleObject(2).intValue();
            CANTIDAD = cs.getOracleObject(3).intValue();    
            DESCRIPCION = cs.getOracleObject(4).stringValue();  
            FOTOByte = cs.getBytes(5);
            InputStream z = new ByteArrayInputStream(FOTOByte);
            BufferedImage FOTO = ImageIO.read(z);
            
            this.JLID_REPUESTO.setText(String.valueOf(IDREPUESTO));
            System.out.println("IMPRIMIENDO FOTO: "+FOTO);             
            System.out.println(CANTIDAD);            
            System.out.println(DESCRIPCION);            
            System.out.println("TERMINO CARGA REPUESTO");
            
            this.JTDESCREPU.setText(DESCRIPCION);
            JPanelImagen.add(new miPanel(FOTO, JPanelImagen.getSize()));
            JPanelImagen.setVisible(true);
            JPanelImagen.repaint();
            this.JFCantidad.setEnabled(true);
            
        } catch (IOException ex) {           
            Logger.getLogger(RetiroRepuesto.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("PROBLEMA1");
        } catch (SQLException ex) {
        
            Logger.getLogger(RetiroRepuesto.class.getName()).log(Level.SEVERE, null, ex);


        } catch (NullPointerException ex){
               // JOptionPane.showMessageDialog(rootPane, "El Repuesto no tiene STOCK, no puede retirar repuesto seleccionado", "Mensajero", JOptionPane.WARNING_MESSAGE);                
                Logger.getLogger(RetiroRepuesto.class.getName()).log(Level.SEVERE, null, ex);
                LimpiarCampos();
                
        }
            
            
        
        
}//GEN-LAST:event_jButton7ActionPerformed

private void JFCantidadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JFCantidadMouseExited
        
}//GEN-LAST:event_JFCantidadMouseExited

private void JFCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFCantidadActionPerformed
  
}//GEN-LAST:event_JFCantidadActionPerformed

private void JFCantidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JFCantidadFocusLost

}//GEN-LAST:event_JFCantidadFocusLost

private void JFCantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JFCantidadKeyPressed
    
}//GEN-LAST:event_JFCantidadKeyPressed

private void JFCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JFCantidadKeyReleased
    
}//GEN-LAST:event_JFCantidadKeyReleased

private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
    System.out.println("Inicio Definición Variables");
    int NRO_FACTURA = Integer.parseInt(JFNROFACTURA2.getText().trim());    
    int IDREPUESTO = Integer.parseInt(this.JLID_REPUESTO.getText().trim());
    String DETALLE = this.JTObservaciones.getText().trim().toUpperCase();
    int CANTIDAD = Integer.parseInt(this.JFCantidad.getText().trim());    
                
    System.out.println("Termino Definición Variables");
    Conexion c = new Conexion();            
               
    System.out.println("NRO_FACTURA: " +Integer.parseInt(JFNROFACTURA2.getText()));
    System.out.println("IDREPUESTO: " +IDREPUESTO);
    System.out.println("OBSERVACIONES: " +DETALLE);
    System.out.println("CANTIDAD: " +CANTIDAD);
    
                
                
            if(this.JFNROFACTURA2.getText().trim() != null && this.JFCantidad.getText() != null && this.JTObservaciones.getText() != null) {
                int n = JOptionPane.showConfirmDialog(rootPane, "¿Está seguro que desea Guardar?", "Mensajero", JOptionPane.YES_NO_CANCEL_OPTION);
                //n = 0 es YES, n = 1 es NO, n = 2 es Cancel
                if (n == 0) {
                 
                        c.RegistrarCompraRepuesto(NRO_FACTURA, IDREPUESTO, CANTIDAD, DETALLE);
                        this.JLREPINGRESADO.add(this.JFCantidad.getText() + " " +this.JTRepueSelec.getText());                        
                        LimpiarCampos();
                        //contador = 1;
                //JOptionPane.showMessageDialog(null, "Se ha producido un error en la inserción", "Error", JOptionPane.ERROR_MESSAGE);
                
            } else if (n == 1) {
                this.JFNROFACTURA2.setText(null);
                LimpiarCampos();
                this.JLREPDISPO.removeAll();
                this.JFCantidad.setEnabled(false);
      }

        }
        else{
            JOptionPane.showMessageDialog(null,"Codigo: " +"Debe llenartodos los campos solicitados", "Error", JOptionPane.ERROR_MESSAGE); 
        }
                
}//GEN-LAST:event_jButton9ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox JCADMINISTRADOR;
    private javax.swing.JComboBox JCPROVEEDOR;
    private javax.swing.JFormattedTextField JFCantidad;
    private javax.swing.JFormattedTextField JFNROFACTURA;
    private javax.swing.JFormattedTextField JFNROFACTURA2;
    private javax.swing.JLabel JLIDPROVEEDOR;
    private javax.swing.JLabel JLID_REPUESTO;
    private java.awt.List JLREPDISPO;
    private java.awt.List JLREPINGRESADO;
    private javax.swing.JPanel JPanelImagen;
    private javax.swing.JTextArea JTDESCREPU;
    private javax.swing.JTextArea JTObservaciones;
    private javax.swing.JTextField JTRepueSelec;
    private javax.swing.JTextArea JTXDETALLE;
    private javax.swing.JComboBox TCINI1;
    private javax.swing.JComboBox TCINI2;
    private javax.swing.JComboBox TCINI3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
