/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RetiroRepuesto.java
 *
 * Created on Apr 29, 2012, 2:31:53 AM
 */
package soprafamrv;

import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import oracle.jdbc.OracleCallableStatement;
import soprafamrv.BD.Conexion;
import soprafamrv.SISTEMA.miPanel;
import soprafamrv.SISTEMA.ot;
import soprafamrv.SISTEMA.repuesto;

/**
 *
 * @author Cri
 */
public class RetiroRepuesto extends javax.swing.JInternalFrame {

    /** Creates new form RetiroRepuesto */
    public RetiroRepuesto() throws SQLException {
        initComponents();
        this.JLID_REPUESTO.setVisible(false);

    }
    
     static protected String RUT = null;
     private void CargarOT() throws SQLException {
        this.TablaOTRR.removeAll();
        String query = "select * from DATOSOTServicio";
        ResultSet rs = Conexion.ejecutarQuery(query);
        ot.llenarTablaOT(TablaOTRR, rs);
        
        
     }
     
     private void CargarRepuestos() throws SQLException{
        String query = "Select nombre from repuesto";
        ResultSet rs = Conexion.ejecutarQuery(query);
        while (rs.next()) {
            this.JLRepuDispo.add(rs.getString("nombre"));
         }
    }
     private void LimpiarCampos(){
         this.JTRepueSelec.setText(null);
         this.JTStock.setText(null);
         this.JTDESCREPU.setText(null);
         this.JFCantidad.setText(null);       
         this.JTObservaciones.setText(null);
         JPanelImagen.removeAll();
         JPanelImagen.repaint();
     }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TablaOTRR = new javax.swing.JTable();
        jPanel16 = new javax.swing.JPanel();
        jButton19 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        JBCargarOT = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        JTRDSNUMORDEN = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        JLRepuDispo = new java.awt.List();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        JTRepueSelec = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JTStock = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTDESCREPU = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        JFCantidad = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        JPanelImagen = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTObservaciones = new javax.swing.JTextArea();
        jButton9 = new javax.swing.JButton();
        JTRSPATENTE = new javax.swing.JFormattedTextField();
        JTRDSMARCA = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        JTRDSMODELO = new javax.swing.JFormattedTextField();
        JLID_REPUESTO = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        JTABLAOTREP = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(soprafamrv.SOPRAFAMRVApp0.class).getContext().getResourceMap(RetiroRepuesto.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel1.border.title"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel15.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, resourceMap.getColor("jPanel15.border.titleColor"))); // NOI18N
        jPanel15.setAutoscrolls(true);
        jPanel15.setName("jPanel15"); // NOI18N

        jScrollPane5.setName("jScrollPane5"); // NOI18N

        TablaOTRR.setAutoCreateRowSorter(true);
        TablaOTRR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TablaOTRR.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        TablaOTRR.setName("TablaOTRR"); // NOI18N
        TablaOTRR.getTableHeader().setReorderingAllowed(false);
        TablaOTRR.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TablaOTRRFocusGained(evt);
            }
        });
        jScrollPane5.setViewportView(TablaOTRR);

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel16.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, resourceMap.getColor("jPanel16.border.titleColor"))); // NOI18N
        jPanel16.setName("jPanel16"); // NOI18N

        jButton19.setText(resourceMap.getString("jButton19.text")); // NOI18N
        jButton19.setName("jButton19"); // NOI18N
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jLabel25.setText(resourceMap.getString("jLabel25.text")); // NOI18N
        jLabel25.setName("jLabel25"); // NOI18N

        jRadioButton7.setText(resourceMap.getString("jRadioButton7.text")); // NOI18N
        jRadioButton7.setName("jRadioButton7"); // NOI18N

        jRadioButton8.setText(resourceMap.getString("jRadioButton8.text")); // NOI18N
        jRadioButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jRadioButton8.setName("jRadioButton8"); // NOI18N

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addComponent(jButton19)
                .addGap(22, 22, 22))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel25)
                .addComponent(jRadioButton7)
                .addComponent(jRadioButton8))
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jButton19))
        );

        JBCargarOT.setText(resourceMap.getString("JBCargarOT.text")); // NOI18N
        JBCargarOT.setName("JBCargarOT"); // NOI18N
        JBCargarOT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCargarOTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, 0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBCargarOT, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBCargarOT))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel3.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, resourceMap.getColor("jPanel3.border.titleColor"))); // NOI18N
        jPanel3.setName("jPanel3"); // NOI18N

        JTRDSNUMORDEN.setEditable(false);
        JTRDSNUMORDEN.setEnabled(false);
        JTRDSNUMORDEN.setName("JTRDSNUMORDEN"); // NOI18N

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel4.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, resourceMap.getColor("jPanel4.border.titleColor"))); // NOI18N
        jPanel4.setName("jPanel4"); // NOI18N

        jButton7.setText(resourceMap.getString("jButton7.text")); // NOI18N
        jButton7.setName("jButton7"); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        JLRepuDispo.setName("JLRepuDispo"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(JLRepuDispo, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(JLRepuDispo, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7))
        );

        jSeparator1.setName("jSeparator1"); // NOI18N

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel6.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, resourceMap.getColor("jPanel6.border.titleColor"))); // NOI18N
        jPanel6.setName("jPanel6"); // NOI18N

        JTRepueSelec.setText(resourceMap.getString("JTRepueSelec.text")); // NOI18N
        JTRepueSelec.setEnabled(false);
        JTRepueSelec.setName("JTRepueSelec"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        JTStock.setText(resourceMap.getString("JTStock.text")); // NOI18N
        JTStock.setEnabled(false);
        JTStock.setName("JTStock"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        JTDESCREPU.setColumns(20);
        JTDESCREPU.setEditable(false);
        JTDESCREPU.setLineWrap(true);
        JTDESCREPU.setRows(5);
        JTDESCREPU.setEnabled(false);
        JTDESCREPU.setName("JTDESCREPU"); // NOI18N
        jScrollPane1.setViewportView(JTDESCREPU);

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        JFCantidad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#####"))));
        JFCantidad.setText(resourceMap.getString("JFCantidad.text")); // NOI18N
        JFCantidad.setEnabled(false);
        JFCantidad.setName("JFCantidad"); // NOI18N
        JFCantidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JFCantidadMouseExited(evt);
            }
        });
        JFCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFCantidadActionPerformed(evt);
            }
        });
        JFCantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JFCantidadFocusLost(evt);
            }
        });
        JFCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JFCantidadKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JFCantidadKeyReleased(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel2.border.title"))); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N

        JPanelImagen.setName("JPanelImagen"); // NOI18N

        javax.swing.GroupLayout JPanelImagenLayout = new javax.swing.GroupLayout(JPanelImagen);
        JPanelImagen.setLayout(JPanelImagenLayout);
        JPanelImagenLayout.setHorizontalGroup(
            JPanelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 219, Short.MAX_VALUE)
        );
        JPanelImagenLayout.setVerticalGroup(
            JPanelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 233, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        JTObservaciones.setColumns(20);
        JTObservaciones.setLineWrap(true);
        JTObservaciones.setRows(5);
        JTObservaciones.setName("JTObservaciones"); // NOI18N
        jScrollPane2.setViewportView(JTObservaciones);

        jButton9.setText(resourceMap.getString("jButton9.text")); // NOI18N
        jButton9.setName("jButton9"); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(JTRepueSelec, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(18, 18, 18)
                                                .addComponent(JFCantidad, 0, 0, Short.MAX_VALUE))
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(JTStock, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton9))
                        .addGap(39, 39, 39)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(JTRepueSelec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(JTStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JFCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(17, 17, 17)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9)
                .addGap(42, 42, 42))
        );

        JTRSPATENTE.setEditable(false);
        JTRSPATENTE.setEnabled(false);
        JTRSPATENTE.setName("JTRSPATENTE"); // NOI18N

        JTRDSMARCA.setEditable(false);
        JTRDSMARCA.setEnabled(false);
        JTRDSMARCA.setName("JTRDSMARCA"); // NOI18N

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        jLabel21.setText(resourceMap.getString("jLabel21.text")); // NOI18N
        jLabel21.setName("jLabel21"); // NOI18N

        jLabel22.setText(resourceMap.getString("jLabel22.text")); // NOI18N
        jLabel22.setName("jLabel22"); // NOI18N

        JTRDSMODELO.setEditable(false);
        JTRDSMODELO.setEnabled(false);
        JTRDSMODELO.setName("JTRDSMODELO"); // NOI18N

        JLID_REPUESTO.setText(resourceMap.getString("JLID_REPUESTO.text")); // NOI18N
        JLID_REPUESTO.setName("JLID_REPUESTO"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTRDSMODELO)
                            .addComponent(JTRDSMARCA)
                            .addComponent(JTRSPATENTE, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLID_REPUESTO)
                            .addComponent(JTRDSNUMORDEN, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(JTRSPATENTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTRDSNUMORDEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(JTRDSMARCA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLID_REPUESTO))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(JTRDSMODELO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel5.border.title"))); // NOI18N
        jPanel5.setName("jPanel5"); // NOI18N

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        JTABLAOTREP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        JTABLAOTREP.setName("JTABLAOTREP"); // NOI18N
        JTABLAOTREP.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(JTABLAOTREP);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        jMenu1.setText(resourceMap.getString("jMenu1.text")); // NOI18N
        jMenu1.setName("jMenu1"); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu2.setText(resourceMap.getString("jMenu2.text")); // NOI18N
        jMenu2.setName("jMenu2"); // NOI18N
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void TablaOTRRFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TablaOTRRFocusGained
// TODO add your handling code here:
}//GEN-LAST:event_TablaOTRRFocusGained

private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jButton19ActionPerformed

private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            LimpiarCampos();         
            String NOMBRE = this.JLRepuDispo.getSelectedItem();                            
            this.JTRepueSelec.setText(NOMBRE);
            Connection con = DriverManager.getConnection(Conexion.url, Conexion.usuario, Conexion.clave);
            OracleCallableStatement cs = (OracleCallableStatement) con.prepareCall("BEGIN CargaRepuestos(?,?,?,?,?); END;");
            
            System.out.println("***INICIO CARGA REPUESTO***");
            System.out.println("Setiando Parametros ENTRADA");
            cs.setString(1, NOMBRE);

            System.out.println("Setiando Parametros SALIDA");            
            cs.registerOutParameter(2, Types.INTEGER);            
            cs.registerOutParameter(3, Types.INTEGER);            
            cs.registerOutParameter(4, Types.VARCHAR);            
            cs.registerOutParameter(5, Types.BLOB);
            System.out.println("TERMINO Seteo de Parametros");                                                
            
            cs.execute();
            int IDREPUESTO = 0;
            int CANTIDAD = 0;
            String DESCRIPCION = null;
            byte[] FOTOByte;
            
            //Asignacion a las variables
            System.out.println("INICIO ASIGNACION VARIABLES OBTENIDAS DE BD");                                                
            
            IDREPUESTO = cs.getOracleObject(2).intValue();
            CANTIDAD = cs.getOracleObject(3).intValue();             
            DESCRIPCION = cs.getOracleObject(4).stringValue();  
            FOTOByte = cs.getBytes(5);
            InputStream z = new ByteArrayInputStream(FOTOByte);
            BufferedImage FOTO = ImageIO.read(z);
            
            this.JLID_REPUESTO.setText(String.valueOf(IDREPUESTO));
            System.out.println("IMPRIMIENDO FOTO: "+FOTO);             
            System.out.println(CANTIDAD);            
            System.out.println(DESCRIPCION);            
            System.out.println("TERMINO CARGA REPUESTO");
            
            this.JTStock.setText(String.valueOf(CANTIDAD));
            this.JTDESCREPU.setText(DESCRIPCION);
            JPanelImagen.add(new miPanel(FOTO, JPanelImagen.getSize()));
            JPanelImagen.setVisible(true);
            JPanelImagen.repaint();
            this.JFCantidad.setEnabled(true);
            
        } catch (IOException ex) {           
            Logger.getLogger(RetiroRepuesto.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("PROBLEMA1");
        } catch (SQLException ex) {
        
            Logger.getLogger(RetiroRepuesto.class.getName()).log(Level.SEVERE, null, ex);


        } catch (NullPointerException ex){
                JOptionPane.showMessageDialog(rootPane, "El Repuesto no tiene STOCK, no puede retirar repuesto seleccionado", "Mensajero", JOptionPane.WARNING_MESSAGE);                
                Logger.getLogger(RetiroRepuesto.class.getName()).log(Level.SEVERE, null, ex);
                LimpiarCampos();
                
        }
            
            
        
        
}//GEN-LAST:event_jButton7ActionPerformed

private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
    System.out.println("Inicio Definición Variables");
    int NUM_ORDEN = Integer.parseInt(JTRDSNUMORDEN.getText().trim());    
    String PATENTE = this.JTRSPATENTE.getText().trim().toUpperCase();
    int IDREPUESTO = Integer.parseInt(this.JLID_REPUESTO.getText().trim());
    String OBSERVACIONES = this.JTObservaciones.getText().trim().toUpperCase();
    int CANTIDAD = Integer.parseInt(this.JFCantidad.getText().trim());
    String RUT_ENCARGADO = RUT.trim();
                
    System.out.println("Termino Definición Variables");
    Conexion c = new Conexion();            
               
    System.out.println("NUM_ORDEN: " +Integer.parseInt(JTRDSNUMORDEN.getText()));
    System.out.println("PATENTE: " +JTRSPATENTE.getText());
    System.out.println("IDREPUESTO: " +IDREPUESTO);
    System.out.println("OBSERVACIONES: " +OBSERVACIONES);
    System.out.println("CANTIDAD: " +CANTIDAD);
    System.out.println ("RUT: " +RUT_ENCARGADO);
                
                
            if(this.JTRSPATENTE.getText().trim() != null && this.JTRDSMARCA.getText().trim() != null && this.JTRDSMODELO.getText().trim() != null && this.JTRDSNUMORDEN.getText().trim() != null && this.JFCantidad.getText() != null && this.JTObservaciones.getText() != null) {
                int n = JOptionPane.showConfirmDialog(rootPane, "¿Está seguro que desea Guardar?", "Mensajero", JOptionPane.YES_NO_CANCEL_OPTION);
                //n = 0 es YES, n = 1 es NO, n = 2 es Cancel
                if (n == 0) {
                    try {
                        c.RegistrarRepuestoOT(NUM_ORDEN, PATENTE, IDREPUESTO, RUT_ENCARGADO, OBSERVACIONES, CANTIDAD);
                        this.TablaOTRR.removeAll();
                        String query = "select * from ORDEN_TRABAJO_REPUESTO WHERE ID_OT= "+NUM_ORDEN+" AND PATENTE= '"+PATENTE+"'";
                        ResultSet rs = Conexion.ejecutarQuery(query);
                        ot.llenarTablaOT(JTABLAOTREP, rs);
                        
                        this.JTRSPATENTE.setText(null);
                        this.JTRDSMARCA.setText(null);
                        this.JTRDSMODELO.setText(null);
                        this.JTRDSNUMORDEN.setText(null);
                        LimpiarCampos();
                        this.JLRepuDispo.removeAll();
                        this.JFCantidad.setEnabled(false);
                        
                
                //contador = 1;
                } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Se ha producido un error en la inserción", "Error", JOptionPane.ERROR_MESSAGE);
                
                }        
                
            } else if (n == 1) {
                this.JTRSPATENTE.setText(null);
                this.JTRDSMARCA.setText(null);
                this.JTRDSMODELO.setText(null);
                this.JTRDSNUMORDEN.setText(null);
                LimpiarCampos();
                this.JLRepuDispo.removeAll();
                this.JFCantidad.setEnabled(false);
      }

        }
        else{
            JOptionPane.showMessageDialog(null,"Codigo: " +"Debe llenartodos los campos solicitados", "Error", JOptionPane.ERROR_MESSAGE); 
        }
                
}//GEN-LAST:event_jButton9ActionPerformed

private void JBCargarOTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCargarOTActionPerformed
        try {
            this.JTABLAOTREP.removeAll();
            int y = this.TablaOTRR.getSelectedColumn();    
            int x = this.TablaOTRR.getSelectedRow();        
            String idot = (String) TablaOTRR.getValueAt(x,0);    
            String patente = (String) TablaOTRR.getValueAt(x,1); 
            String marca =  (String) TablaOTRR.getValueAt(x,2);    
            String modelo = (String) TablaOTRR.getValueAt(x,3);    
            this.JTRSPATENTE.setText(patente);
            this.JTRDSMARCA.setText(marca);
            this.JTRDSMODELO.setText(modelo);
            this.JTRDSNUMORDEN.setText(idot);
            CargarRepuestos();
        } catch (SQLException ex) {
            Logger.getLogger(RetiroRepuesto.class.getName()).log(Level.SEVERE, null, ex);
        }
            


}//GEN-LAST:event_JBCargarOTActionPerformed

private void JFCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFCantidadActionPerformed
  
}//GEN-LAST:event_JFCantidadActionPerformed

private void JFCantidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JFCantidadFocusLost

}//GEN-LAST:event_JFCantidadFocusLost

private void JFCantidadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JFCantidadMouseExited
        if(Integer.parseInt(this.JFCantidad.getText()) > Integer.parseInt(this.JTStock.getText())) {
        JOptionPane.showMessageDialog(rootPane, "La cantidad seleccionada excede el Stock en Bodega", "Mensajero", JOptionPane.WARNING_MESSAGE);                
        this.JFCantidad.setText(null);
    }

}//GEN-LAST:event_JFCantidadMouseExited

private void JFCantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JFCantidadKeyPressed
    if(Integer.parseInt(this.JFCantidad.getText()) > Integer.parseInt(this.JTStock.getText())) {
        JOptionPane.showMessageDialog(rootPane, "La cantidad seleccionada excede el Stock en Bodega", "Mensajero", JOptionPane.WARNING_MESSAGE);                
        this.JFCantidad.setText(null);
    }

}//GEN-LAST:event_JFCantidadKeyPressed

private void JFCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JFCantidadKeyReleased
    if(Integer.parseInt(this.JFCantidad.getText()) > Integer.parseInt(this.JTStock.getText())) {
        JOptionPane.showMessageDialog(rootPane, "La cantidad seleccionada excede el Stock en Bodega", "Mensajero", JOptionPane.WARNING_MESSAGE);                
        this.JFCantidad.setText(null);
    }

}//GEN-LAST:event_JFCantidadKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBCargarOT;
    private javax.swing.JFormattedTextField JFCantidad;
    private javax.swing.JLabel JLID_REPUESTO;
    private java.awt.List JLRepuDispo;
    private javax.swing.JPanel JPanelImagen;
    private javax.swing.JTable JTABLAOTREP;
    private javax.swing.JTextArea JTDESCREPU;
    private javax.swing.JTextArea JTObservaciones;
    private javax.swing.JFormattedTextField JTRDSMARCA;
    private javax.swing.JFormattedTextField JTRDSMODELO;
    private javax.swing.JFormattedTextField JTRDSNUMORDEN;
    private javax.swing.JFormattedTextField JTRSPATENTE;
    private javax.swing.JTextField JTRepueSelec;
    private javax.swing.JTextField JTStock;
    private javax.swing.JTable TablaOTRR;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
